### ISSUE TITLE
How to track finger position?

### ISSUE THREAD

**Issue by fobus42** [ilmente/mnTouch#10]
I'm trying to develop a angular applicaition like you, but I need the fingers position when user swipes it. Is it possible to reach with this plugin?

I mean I need all positions real time.

Thanks.

**Comment by ilmente** [comment]
HI @fobus42,
sorry for this late answer! 
This plugin doesn't provide these informations: they are too fine and getting theme would decrease the performance. Sorry.
Anyway I think you can get them in real time, maybe it's heavy for rendering, but it's still possible. But not with this plugin.

Best. 
Ale
