### ISSUE TITLE
MIssing bower.json file

### ISSUE THREAD

**Issue by DEllingsworth** [ilmente/mnTouch#2]
Without a bower.json file, users can't install the code with
bower install ilmente/mnTouch -S
grunt bower-install 

And have the references added to index.html etc.

**Comment by lutechmobile** [comment]
You're right. 
I accepted your pull request. Now I have to test it.
Thanks.

**Comment by ilmente** [comment]
You're right. 
I accepted your pull request. Now I have to test it.
Thanks.
