### ISSUE TITLE
request: hold return the closest element

### ISSUE THREAD

**Issue by DEllingsworth** [ilmente/mnTouch#3]
When returning the element for hold , mnTouch currently returns the element that the directive was placed on.  Is it possible to add an option to return the actual element touched?  

Code pen showing the difference between ionic and mnTouch
http://codepen.io/dellingsworth/pen/wBdQzr

**Comment by ilmente** [comment]
I'll check.
I have to evaluate if this edit it's inside the project scope, than I'll write you back. 
Give me some day.
Thanks.

**Comment by ilmente** [comment]
I checked: you can get the sender element this way: `$event.events.start.target` for the "starter" element, or `$event.events.end.target` if you need the last element the mouse hovered over.

Hope it'll be useful. Let me know!
Check it out on the repo: I have updated the test files.

**Comment by DEllingsworth** [comment]
Not sure, but when i use the start element, it does position the popup where i clicked

**Comment by DEllingsworth** [comment]
Thanks, that helps!
