### ISSUE TITLE
$event.PreventDefault() undefined

### ISSUE THREAD

**Issue by zenny-ritchie** [ilmente/mnTouch#6]
When i try to prevent default browser scroll there is no prevent default function in return object. Is there a way to disable default browser scroll?

**Comment by lutechmobile** [comment]
Sorry I'm answering with some delay.
If you look at the event object returned, you'll find `events.start` and `events.stop` props, that are the real events.

In angular:

```
$scope.secureTap = function($event){
	$event.events.start.preventDefault();
        $event.events.end.preventDefault();
	...
};
```

Each event on mnTouch is a composit event, created upon browser native events, so you can choose what event to stop. They are fired in  different time, so you would probably decide to stop one of them or both. 
I tried to incapsulate a function for that, but it will mean a lost in control over the events, a lost that I think it's not useful.
From now I'll work hard on this directive, so write to me or let me know if I miss the point!

**Comment by ilmente** [comment]
Sorry I'm answering with some delay.
If you look at the event object returned, you'll find `events.start` and `events.end` props, that are the real events.

In angular:

```
$scope.secureTap = function($event){
    $event.events.start.preventDefault();
    $event.events.end.preventDefault();
    ...
};
```

Each event on mnTouch is a composite event, created upon browser native events, so you can choose what event to stop. They are fired in different times, so you would probably decide to stop one or both of them (tap -not secure- has only start event). 
I tried to incapsulate a function for that, but it will mean a lost in control over the events, a lost that I think it's not useful.
From now I'll work hard on this directive, so write to me or let me know if I miss the point!
