### ISSUE TITLE
Need a release event

### ISSUE THREAD

**Issue by HugoHeneault** [ilmente/mnTouch#8]
Hi there. 

Thanks a lot for your great directive! It saved me from ionic on-hold event not working on Android. 
Could you just add a `release` when `hold` is released?

Thanks! :smiley:

**Comment by abelspry** [comment]
Hi, thanks! 
Can you be more specific regarding `release`? Is that an event, a handler or something else?

**Comment by ilmente** [comment]
Hi, thanks! 
Can you be more specific regarding release? Is that an event, a handler or something else?

**Comment by ilmente** [comment]
Hi @HugoHeneault,
can you give me some more specs? Otherwise I will close this request.
Thanks.
